### ISSUE TITLE
Liens vers les gazettes cassés dans le readme

### ISSUE THREAD

**Issue by fBedecarrats** [DISIC/gazette-bluehats#12]
Bonjour, les liens vers les numéros de la gazette mentionnés dans le fichier readme son cassés.

**Comment by nqb** [comment]
Bonjour,
Ils sont ici: https://github.com/DISIC/gazette-bluehats/tree/master/content/post

Ceci fait suite au changement introduit par la PR de création d'un site statique: https://disic.github.io/gazette-bluehats/

**Comment by bzg** [comment]
C'est corrigé, merci beaucoup !
