### ISSUE TITLE
gazette n°4 - problème avec les liens en .org

### ISSUE THREAD

**Issue by sycom** [DISIC/gazette-bluehats#15]
Il semble que tous les liens se terminant en .org de la gazette 4 aient sauté (framasoft.org, scenari.org...) 
Je n'ai pas vu le problème équivalent sur la gazette 3 (ow2.org, jitsi.org sont passés).

Apparemment, c'est à la génération du html, [dès le premier commit sur le fichier](https://github.com/DISIC/gazette-bluehats/commit/76a5b00c68de8492888e17660b9a385bfff433ad#diff-0cfdfd869367abe1511a3df568bb3987). Le markdown est ok de son côté.

**Comment by bzg** [comment]
Ca devrait être corrigé - il faudrait que je voie si c'est un problème avec le module [jekyll-org](https://github.com/eggcaker/jekyll-org).

**Comment by sycom** [comment]
Pour l'heure, la page conserve les liens erronés. A vrai dire, il y a des mystères. Les pages semblent avoir été rafraichies ce matin à 11:43, mais la gazette 3 rend les .org comme il faut et pas la gazette 4 :-/...
Ça n'a sans doute rien à voir, mais c'est normal que le générateur annoncé par les pages soit Hugo? (c'est juste le template j'imagine)

**Comment by bzg** [comment]
Grosse fatigue. Oui, c'est du `hugo`! Et j'avais oublié que je devais publier les fichiers statiques en local avant de pousser - voir qui est fait. Merci !
