### ISSUE TITLE
Logiciel : LibreOffice version 7.0

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [DISIC/gazette-bluehats#16]
https://wiki.documentfoundation.org/ReleaseNotes/7.0/fr#Am.C3.A9lioration_de_l.27accessibilit.C3.A9

La récente version 7.0 de LibreOffice intègre deux fonctionnalités expérimentales liées à l’accessibilité :
1. le support du format [PDF/UA](https://en.wikipedia.org/wiki/PDF/UA) (Universal Accessibility) en export ;
2. un assistant de vérification de plusieurs points d’accessibilité : 
 - absence du titre dans les propriétés du document,
 - contrastes insuffisants entre les textes et leurs fonds,
 - présence de cellules de tableau scindées sur plusieurs pages,
 - etc.

**Comment by bzg** [comment]
C'est noté, merci !

**Comment by bzg** [comment]
C'est intégré, ça part demain. Merci !
