### ISSUE TITLE
Compte-rendu : Les (télé)Rencontres Scenari 2020 ont eu lieu fin octobre

### ISSUE THREAD

**Issue by lalejand** [DISIC/gazette-bluehats#19]
Association Scenari

L'association Scenari, qui fédère les utilisateur⋅rice⋅s du logiciel libre Scenari, a organisé comme chaque année ses "Rencontres" pour écouter la communauté d'utilisateur⋅rice⋅s, faire partager des retours d'expérience et des ateliers, apporter des l'information sur les prochains axes de développement et créer des synergies entre participant⋅e⋅s.
201 personnes se sont inscrites pour visionner les 12 retours d'expérience et les 8 ateliers proposés en modalité asynchrone, et participer aux sessions synchrones de visioconférence les 29-30 octobre. L'association a aussi réalisé son Assemblée Générale annuelle le 28 octobre et à renouvelé son bureau par la même occasion.

https://scenari.org/rencontres2020

**Comment by bzg** [comment]
Inclus dans la gazette de ce mois.
