### ISSUE TITLE
Licence dans fichier LICENSE ? 

### ISSUE THREAD

**Issue by AntoineAugusti** [DISIC/gazette-bluehats#2]
Publier la licence dans le fichier avec un nom anglais ?

**Comment by bzg** [comment]
Tu veux dire qu'il faudrait renommer `LICENCE.md` en `LICENSE` (ou `LICENSE.txt`)?

La LO n'est pas encore détectée par Github, du coup je ne suis pas sûr de voir l'intérêt - mais peut-être que j'ai mal compris ta suggestion.

**Comment by AntoineAugusti** [comment]
C'est simplement que la POCOS recommande d'utiliser le nom anglais. Au moins GitHub se rend compte qu'il y a un fichier de licence, qu'il je le connaît pas et invite à le consulter.

**Comment by bzg** [comment]
Tu as raison.  J'ai renommé en `LICENSE.txt`.  Il faudrait éventuellement référencer cette version `.txt` sur https://www.etalab.gouv.fr/licence-ouverte-open-licence
