### ISSUE TITLE
Logiciel : Annuaire des logiciels, solutions et entreprises du CNLL

### ISSUE THREAD

**Issue by cnuel** [DISIC/gazette-bluehats#21]

**Comment by sfermigier** [comment]
Catherine a peut-être oublié de tirer un lien sur: https://cnll.fr/news/annuaire-des-entreprises-du-cnll-nouvelle-version/

**Comment by bzg** [comment]
Vu, merci pour la précision, j'ai ajouté à la prochaine gazette.

**Comment by bzg** [comment]
C'est publié: https://disic.github.io/gazette-bluehats/gazette_bluehat_10/

Merci !
