### ISSUE TITLE
Logiciel : Open Terms Archive

### ISSUE THREAD

**Issue by clementbiron** [DISIC/gazette-bluehats#22]
Open Terms Archive

_Quel contrat ai-je accepté en utilisant un service numérique ? Les conditions ont-elles changé depuis que j’utilise ces services ? Dans quel sens évoluent-elles ? Sont-elles conformes aux discours de ces acteurs et aux lois qui encadrent leurs pratiques ?_

L'équipe de l'Ambassadeur pour le numérique a développé un outil simple permet désormais de répondre à ces questions : [Open Terms Archive](https://opentermsarchive.org).
C'est un logiciel libre et collaboratif qui permet de suivre les évolutions des des conditions générales des principaux fournisseurs de services en ligne en :
- enregistrant en temps réel chaque publication d'une nouvelle version des documents ;
- affichant spécifiquement les changements appliqués aux documents ;
- disposant d’un corpus documentaire de leur historique.

Open Terms Archive a vocation à s’enrichir et à devenir un Commun sur lequel il sera possible de bâtir de nombreux usages : outils pour la recherche en droit comparé, alertes ciblées, analyses linguistiques.
Les contributeurs sont les bienvenus, pour soumettre de nouveaux services ou documents, améliorer le logiciel pour permettre une suivre un plus grand nombre de langues et de juridiction ou suggérer des modalités de valorisation des études de cas qui pourraient être menées.

A titre de premier usage, nous avons ainsi développé [Scripta Manent](https://disinfo.quaidorsay.fr/fr/open-terms-archive/scripta-manent), un premier outil très simple qui, pour 367 contrats, permet de mesurer toutes les évolutions, ajouts ou suppressions, entre deux dates de votre choix.

Développer des outils ouverts et collaboratifs, au service de la transparence, s’inscrit dans deux des lignes de force de la diplomatie numérique française :
- Incarner une souveraineté numérique européenne c’est-à-dire une réelle autonomie stratégique fondée sur une capacité d’action et de choix : il s’agit, à travers cet outil, de donner du pouvoir aux citoyens, entreprises et régulateurs pour décider librement de leurs pratiques et de leurs rapports vis-à-vis des acteurs numériques ;
- Construire un cadre de régulation du numérique fondé sur le dialogue multilatéral et multiacteurs : la création de biens communs à travers la formation d’alliances rassemblant tous les acteurs du numérique – Etats, société civile, acteurs privés – permet un dialogue continu et constructif autour des valeurs que nous souhaitons porter, et imposer, dans le monde numérique.

N’hésitez pas à nous contacter afin de :
(i) soumettre des services ou documents que vous souhaiteriez suivre. Pour rappel, vous pouvez également ajouter des documents en toute autonomie ;
(ii) suggérer des modalités de valorisation des études de cas qui pourraient être menées ;
(iii) poser toute question quant à l’utilisation de l’outil.
N’hésitez pas non plus à vous approprier cette ressource pour vos propres projets, privés ou publics, y compris entrepreneuriaux.

**Comment by bzg** [comment]
C'est inclus dans le brouillon de la gazette, en cours de validation.  Merci encore !
