### ISSUE TITLE
Offre d'emploi : CoachCO2

### ISSUE THREAD

**Issue by laem** [DISIC/gazette-bluehats#23]
> Je propose ici une offre d'emploi pour la prochaine gazette, il s'agit d'un poste pour une association, pour travailler produire du logiciel libre. Si ce n'est pas adapté à cette gazette (par exemple car ce n'est pas un emploi dans une administration), pas de souci :) 

La Fabrique des mobilités recrute une ou un développeur front sur le sujet du Coach CO2. Il s'agit de construire un logiciel libre qui complétera le logiciel [Tracemob](https://github.com/fabmob/tracemob-phone) pour en visualiser les données sous l'angle de l'empreinte climat de notre mobilité. Tout le code sera libre. 

Plus d'infos ici : https://pad.fabmob.io/fiche-poste-coach-co2

**Comment by bzg** [comment]
C'est noté, merci !

**Comment by bzg** [comment]
Hello @laem, j'ai intégré l'offre au brouillon de la gazette qui part (si tout va bien) demain.  N'hésite pas à me dire si ce n'est plus d'actualité !
