### ISSUE TITLE
Logiciel : Keycloakify

### ISSUE THREAD

**Issue by garronej** [DISIC/gazette-bluehats#24]
[Keycloakify](https://github.com/InseeFrLab/keycloakify)

[Keycloak](https://www.keycloak.org) est un système logiciel serveur qui gère l'identification utilisateur.
En pratique, lorsque vous souhaitez identifier un utilisateur sur votre site, vous le redirigez vers votre instance Keycloak où il pourra créer un compte et rentrer son mot de passe.  
L'utilisateur vous est ensuite renvoyé munie d'un jeton contenant des informations sur son identité.
Keycloak permet notamment d'implémenter l'identification par [**France Connect**](https://franceconnect.gouv.fr) via [cette extension](https://github.com/InseeFr/Keycloak-FranceConnect).

[Keycloakify](https://github.com/InseeFrLab/keycloakify) permet lui de modifier l'aspect visuel des page de connexion et d'enregistrements pour qu'elle s'intègre parfaitement à votre site web.  

![onyxia-ui_demo1](https://user-images.githubusercontent.com/6702424/126913751-82d76047-aeb6-4801-8b18-35e3f26daa36.gif)  

@bzg C'est peut être trop long. Si c'est le cas je pourrais raccourcir.

**Comment by bzg** [comment]
Bonjour @garronej et merci pour la proposition.

La documentation autour du SILL est (pour l'instant) sur [cette page](https://disic.github.io/sill/index.html).

Pour proposer Keycloakify au SILL, il faut ensuite envoyer un email à [sill-mainteneurs@listes.etalab.gouv.fr](mailto:sill-mainteneurs@listes.etalab.gouv.fr) en indiquant:

- A quelle administration tu es rattaché
- Que tu te proposes comme référent SILL
- Quelle est l'utilisation actuelle de Keycloakify dans ton administration
- Quelle version minimale tu recommandes
- Quelle est la licence associée au code source de ce logiciel

S'il y a une entité Wikidata pour Keycloakify, c'est encore mieux: c'est à partir des données Wikidata que nous récupérons et affichons le lien vers le code source, la documentation, etc.  Une entitée exemplaire est celle de [Gimp](https://www.wikidata.org/wiki/Q8038).

Ensuite, on attend en général une semaine que les autres référents SILL aient le temps de réagir, puis nous intégrons le logiciel dans le SILL.

Nous avons justement un point demain de 15h30 à 17h avec les référents disponibles pour aborder divers sujets, si tu es OK je t'y invite, cela te donnera l'occasion de te présenter et de répondre à d'éventuelles questions.

Merci !

**Comment by garronej** [comment]
OK je m'occupe de tout ça. Et oui avec plaisir pour demain.

**Comment by garronej** [comment]
[La page Wikidata](https://www.wikidata.org/wiki/Q107693197)

**Comment by bzg** [comment]
Le logiciel est désormais [référencé](https://sill.etalab.gouv.fr/fr/software?id=227).

**Comment by bzg** [comment]
PS: Les demandes d'ajout dans le SILL se font plutôt via les issues de [ce dépôt](https://github.com/DISIC/sill/issues).
