### ISSUE TITLE
Témoignage : LemonLDAP::NG, le SSO de l'administration

### ISSUE THREAD

**Issue by guimard** [DISIC/gazette-bluehats#3]
## Nom du logiciel libre
[LemonLDAP::NG](https://lemonldap-ng.org/)

## Description courte de ce à quoi sert le logiciel libre

[LemonLDAP::NG](https://lemonldap-ng.org/) est un [Web-SSO](https://fr.wikipedia.org/wiki/Authentification_unique) largement diffusé en France. Il implémente de nombreux protocoles de fédération d'identité parmi lesquels : [SAML](https://fr.wikipedia.org/wiki/Security_assertion_markup_language), [CAS](https://fr.wikipedia.org/wiki/Central_Authentication_Service) et [OpenID-Connect](https://fr.wikipedia.org/wiki/OpenID_Connect) dont l'implémentation a été qualifiée fournisseur d'identité ou de service pour [FranceConnect](https://fr.wikipedia.org/wiki/FranceConnect).

## Administration publique concernée par le témoignage

Tous les ministères français _(à une seule exception près)_ l'utilisent ainsi que de nombreuses collectivités territoriales.

## Témoignage

Aux environs de l'année 2002, parallèlement la gendarmerie et le ministère des finances décident de déployer un SSO. Ce dernier développe un logiciel libre simple pour cet usage : LemonLDAP. La gendarmerie ayant des besoins plus complexes adopte dans un premier temps un logiciel propriétaire mais abandonne cette idée devant le coût et le manque de souplesse. Elle reprend alors le code initial de LemonLDAP et le réécrit pour ses usages. En 2005, la première version complète est publiée en open-source.
Sous financement public initialement, la société Linagora entre dans la communauté LemonLDAP::NG vers 2006. LemonLDAP::NG se diffuse progressivement dans la plupart des administrations, faisant ainsi réaliser plusieurs dizaines de millions d'euros d'économies par an en comparaison avec la [solution de Forgerock](https://www.forgerock.com/platform/access-management/sso), leader du marché.
La communauté LemonLDAP::NG est toujours très active, hébergée par la [fondation OW2](https://www.ow2.org/), associant plusieurs entreprises _[1]_ et le [ST(SI)²](https://fr.wikipedia.org/wiki/Service_des_technologies_et_des_syst%C3%A8mes_d%27information_de_la_S%C3%A9curit%C3%A9_int%C3%A9rieure), et a sorti en 2019 son implémentation _(et sa conception)_ du [SSO-as-a-Service](https://lemonldap-ng.org/documentation/2.0/ssoaas).
En 2018 est né [FusionIAM](https://fusioniam.org/), regroupement des communautés FusionDirectory et LemonLDAP::NG, qui offre une solution globale d'[IAM](https://fr.wikipedia.org/wiki/Gestion_des_identit%C3%A9s_et_des_acc%C3%A8s).

_[1]: notamment [Linagora](https://linagora.com/), [Worteks](https://www.worteks.com/fr/) et [Openside](https://www.opensides.be/)_

**Comment by bzg** [comment]
Merci @guimard pour cette contribution.  Je les passerai toutes en revue quand je ferai le premier brouillon pour la prochaine gazette.

**Comment by guimard** [comment]
@bzg: nous allons en ajouter une autre sur OCS-Inventory _(communauté mourante reprise par la gendarmerie qui a repris son envol quelques années après et fait vivre une startup normande)_.

**Comment by bzg** [comment]
Il y avait déjà une nouvelle sur OCS Inventory publiée dans la gazette n°1, je garde de côté pour une autre édition.

**Comment by coudot** [comment]
@guimard le rôle de Linagora est à nuancer, il y a eu très peu d'investissement sur fond propre, c'est avant tout grâce au financement du ST(SI)² et de quelques autres clients que nous avons pu contribuer à LL::NG. Aujourd'hui, c'est Worteks qui contribue principalement aux côtés su ST(SI)², à la fois via des financements des clients (dont Orange), mais aussi sur des jours de R&D internes.

**Comment by bzg** [comment]
Merci @coudot pour les précisions - le « focus » sera d'autant plus pertinent qu'il est rédigé collaborativement.

**Comment by bzg** [comment]
Envoyé hier dans la gazette n°3, je ferme l'issue. Merci !

**Comment by guimard** [comment]
Super, merci

**Comment by coudot** [comment]
J'ai reçu la gazette également, merci beaucoup pour l'article sur LemonLDAP::NG !
