### ISSUE TITLE
Témoignage : 

### ISSUE THREAD

**Issue by a-legrignou** [DISIC/gazette-bluehats#4]
OCS Inventory NG

Logiciel de gestion de parc informatique avec des fonctions d'inventaire et de télé-déploiement.

https://www.ocsinventory-ng.org/fr/

Logiciel utilisé par la Gendarmerie Nationale et la Police Nationale

La Gendarmerie Nationale a envisagé le déploiement de son 1er poste de travail sous OS libre en 2006. Un inventaire des logiciels utilisés sur le parc informatique s’est alors avéré nécessaire pour évaluer la dépendance à Microsoft. Malheureusement, aucune solution compatible avec Linux et Windows n’était disponible sur le marché à l’époque. Le projet OCS Inventory était certes naissant mais ne permettait pas de centraliser les tâches. La communauté était en outre très réduite. La Gendarmerie s’est donc lancée dans la refonte de cet outil avec pour objectif de l’adapter à son besoin. 

La communauté s'est alors élargie autour du développeur historique avec l’arrivée de  4 gendarmes contributeurs. Une solution s’est rapidement dessinée et le logiciel OCS Inventory NG est né ! Il est  capable de fournir une photographie précise de l’état d’un parc informatique avec des fonctions de télé-déploiement et une configuration centralisée. Il permet ainsi des économies d’échelle (le parc de la Gendarmerie comprend, à titre d’exemple, environ 100 000 machines) et des gains important de coût et de réactivité. L’ensemble des développements réalisés par des gendarmes ont été reversés à la communauté.

OCS Inventory est désormais utilisé dans le monde entier par de nombreux grands comptes. La communauté historique a laissé sa place à une nouvelle formée autour de FactorFX, un industriel qui propose une offre de service dédiée. La Gendarmerie entretient un lien régulier avec les nouveaux acteurs afin de leur faire bénéficier de son expérience dans le cadre des améliorations ou des corrections.

David Croizer
Arnaud Le Grignou

**Comment by bzg** [comment]
Merci !

**Comment by bzg** [comment]
Publié dans la gazette n°1.  Merci encore.
