### ISSUE TITLE
Compte-rendu : Satet Of the Map Fr 2019

### ISSUE THREAD

**Issue by vinber** [DISIC/gazette-bluehats#5]
OpenStreetMap France

Les 14-15-16 juin 2019, durant 3 jours, contributeurs, utilisateurs, représentants de collectivités et d'entreprises gravitant autour du Web et de l'information géographique, chercheurs, mais aussi personnes curieuses de découvrir cette « carte libre du monde » que représente OpenStreetMap, se retrouveront pour partager leurs expériences, se tenir informé, se former, découvrir l'écosystème et les multiples applications - existantes ou à imaginer – autour d'OpenStreetMap.

https://sotm2019.openstreetmap.fr/ pour le programme et le déroulé
Et plus tard https://openstreetmap.fr et https://peertube.openstreetmap.fr/

**Comment by bzg** [comment]
Bonjour, il n'y a pas eu de gazette cet été... et l'information datait un peu pour être incluse dans la gazette d'hier, du coup je l'ai laissée de côté.  S'il y a d'autres informations sur OSM, n'hésitez pas à de nouveau les partager. Merci !
