### ISSUE TITLE
Logiciel : nixpkgs-tungsten, l'intégration TungstenFabric de Cloudwatt 

### ISSUE THREAD

**Issue by nlewo** [DISIC/gazette-bluehats#7]
https://github.com/cloudwatt/nixpkgs-tungsten

Cloudwatt a publié son intégration de TungstenFabric, le composant SDN de son offre IaaS. Cette intégration est basée sur Nix et publiée sous licence MIT. Plus de détails dans l'article de blog  https://dev.cloudwatt.com/en/blog/introducing-nixpkgs-tungsten.html (en anglais seulement).

**Comment by bzg** [comment]
Bonjour, nous n'avons pas pu inclure ceci dans la gazette partie hier: il manque trop d'éléments pour qu'une personne non familière avec ces technologies puissent comprendre.

Pourriez-vous proposer une version plus étoffée que nous reprendrions dans la gazette de décembre?

Merci beaucoup!

**Comment by nlewo** [comment]
Entre temps, Orange a annoncé la fermeture de Cloudwatt. Ce projet risque donc fortement d'être abandonné, faute de mainteneurs:( 
Je clos donc l'issue.

**Comment by bzg** [comment]
Désolé de lire cela, merci d'avoir répondu à l'issue et de l'avoir fermée.
