### ISSUE TITLE
Logiciel : DFIRC ORC

### ISSUE THREAD

**Issue by yaperez-anssi** [DISIC/gazette-bluehats#8]
https://dfir-orc.github.io/

Pour faire face à des incidents d’un genre nouveau, les « Advanced Persistent Threats » (APTs), apparus il y a près de 10 ans, l’ANSSI a dû adapter sa méthodologie de traitement ainsi que son outillage. Créé et utilisé de longue date par les équipes de l’ANSSI, le logiciel de collecte DFIR ORC regroupe un ensemble d’outils qui permettent la recherche, l’extraction et la mise à disposition des données forensiques. Il a été entièrement conçu afin de fonctionner dans l’écosystème Microsoft Windows de façon décentralisée et à grande échelle.

En s’engageant dans une démarche d’ouverture avec la communauté de la sécurité numérique, l’ANSSI souhaite aujourd’hui partager cet outil mature qu’elle utilise au quotidien depuis plusieurs années.

**Comment by yaperez-anssi** [comment]
Actualité ANSSI: https://www.ssi.gouv.fr/actualite/decouvrez-dfir-orc-un-outil-de-collecte-libre-pour-lanalyse-forensique/
News ANSSI (en): https://www.ssi.gouv.fr/en/actualite/dfir-orc-an-open-source-forensics-tool-dedicated-to-artefact-collection/

**Comment by bzg** [comment]
Ce sera dans la prochaine gazette, décalée au 11 octobre. Merci !
