### ISSUE TITLE
Logiciel : OpenCTI

### ISSUE THREAD

**Issue by yaperez-anssi** [DISIC/gazette-bluehats#9]
https://www.opencti.io/

Le projet OpenCTI (Open Cyber Threat Intelligence), développé par l’ANSSI en partenariat avec le CERT-EU, est un outil de gestion et de partage de la connaissance en matière d’analyse de la cybermenace (Threat Intelligence). Initialement conçu pour structurer les informations de l’agence relatives à la menace informatique, la plateforme facilite aussi les interactions entre l’ANSSI et ses partenaires. L’outil, intégralement libre, est aujourd’hui disponible à l’usage de l’ensemble des acteurs de la « threat intelligence ». L’application leur permettra ainsi de stocker, organiser, visualiser et partager leurs propres connaissances en la matière.

**Comment by yaperez-anssi** [comment]
Actualité ANSSI: https://www.ssi.gouv.fr/actualite/opencti-la-solution-libre-pour-traiter-et-partager-la-connaissance-de-la-cybermenace/
News ANSSI (en): https://www.ssi.gouv.fr/en/actualite/opencti-the-open-source-solution-for-processing-and-sharing-threat-intelligence-knowledge/
Documentation: https://opencti-platform.github.io/docs/getting-started/introduction

**Comment by bzg** [comment]
Ce sera dans la prochaine gazette, décalée au 11 octobre. Merci !
